[package]
authors = ["Gleb Kozyrev <gleb@gkoz.com>"]
name = "build-helper"
version = "0.1.0"

[features]
default = ["resources"]
resources = ["xml-rs"]

[dependencies]
xml-rs = { version = "0.3.0", optional = true }
